[package]
name = "blink"
version = "0.1.0"
authors = ["Michael Daffin <michael@daffin.io>"]
build = "build.rs"

[profile.dev]
lto = false
panic = "abort"

[profile.release]
lto = true
panic = "abort"
